--This file creates P1.Customer and P1.Account tables. P1.Customer stores all bank customers and their information
--      P1.Account stores account specific information. These tables share the ID attribute.

CREATE TABLE P1.Customer (
    ID int NOT NULL GENERATED BY DEFAULT AS IDENTITY (START WITH 100, INCREMENT BY 1, NO CACHE),
    Name varchar(15) NOT NULL,
    Gender char NOT NULL CHECK(Gender='M' OR Gender='F'),
    Age int NOT NULL CHECK(Age>=0),
    Pin int NOT NULL CHECK(Pin>=0),
    PRIMARY KEY(ID)
);

CREATE TABLE P1.Account (
    Number int NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1000, INCREMENT BY 1, NO CACHE),
    ID int NOT NULL,
    Balance int NOT NULL CHECK(Balance>=0),
    Type char NOT NULL CHECK(Type='C' OR Type='S'),
    Status char NOT NULL CHECK(Status='A' OR Status='I'),
    PRIMARY KEY(Number),
    FOREIGN KEY (ID) REFERENCES P1.Customer(ID)
);

CREATE VIEW Total AS (
    SELECT C.NAME, C.Id, C.Age, C.Gender SUM(Balance) AS Total
    FROM P1.Account AS A, P1.Customer AS C
    WHERE A.Id=C.Id AND A.Status='A'
    GROUP BY C.Name,C.Id,C.Age,C.Gender
);
